name: Doffer scrape → CSV

on:
  workflow_dispatch:
    inputs:
      year:
        description: 'Tax year to scrape (e.g., 2024)'
        required: true
        default: '2024'

jobs:
  scrape:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: doffer
        ports: ['5432:5432']
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=10

    env:
      # nyc-doffer needs these:
      DATABASE_URL: postgresql://postgres:postgres@localhost:5432/doffer
      NYCDB_URL: postgresql://postgres:postgres@localhost:5432/doffer
      PUPPETEER_ARGS: --no-sandbox --disable-setuid-sandbox --disable-dev-shm-usage

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node 18
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Setup Python (for NYCDB CLI)
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: System deps (pdftotext for PDFs)
        run: |
          sudo apt-get update
          sudo apt-get install -y poppler-utils wget

      - name: Install Xpdf pdftotext 4.05 (the one doffer expects)
        run: |
          wget -q https://dl.xpdfreader.com/xpdf-tools-linux-4.05.tar.gz
          tar xzf xpdf-tools-linux-4.05.tar.gz
          echo "PDFTOTEXT=$PWD/xpdf-tools-linux-4.05/bin64/pdftotext" >> $GITHUB_ENV

      - name: Install node deps & build
        run: |
          corepack enable
          yarn
          yarn build

      - name: Install NYCDB and load HPD registrations (for BBL list)
        run: |
          python -m pip install --upgrade pip nycdb
          # download + load the HPD registrations table into the same Postgres
          nycdb -U postgres -P postgres -H localhost -D doffer --download hpd_registrations
          nycdb -U postgres -P postgres -H localhost -D doffer --load hpd_registrations
          nycdb -U postgres -P postgres -H localhost -D doffer --verify hpd_registrations

      - name: Build job table, scrape year, export CSV
        run: |
          # 1) make a doffer job table named "boop" from NYCDB's HPD regs
          node dbtool.js build_bbl_table boop hpd_registrations
          # 2) scrape (limit to the chosen year)
          node dbtool.js scrape boop --only-year=${{ github.event.inputs.year }} --only-soa
          # 3) export results
          node dbtool.js output_csv boop > doffer_units.csv

      - name: Upload CSV artifact
        uses: actions/upload-artifact@v4
        with:
          name: doffer_units_${{ github.event.inputs.year }}
          path: doffer_units.csv
